# Generated by Django 5.2.17 on 2026-09-12 16:21

import django.db.models.deletion
import inquiries.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', inquiries.storage.PrivateFileField(max_length=255, upload_to=inquiries.storage.hashed_private_path)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('bytes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('contact', 'Contact Wjeen'), ('vendor', 'Service provider'), ('career', 'Career')], max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], db_index=True, default='new', max_length=16)),
                ('locale', models.CharField(default='en', max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('message', models.TextField(blank=True, default='')),
                ('send_to', models.CharField(blank=True, choices=[('ceo', 'ceo'), ('executive_director', 'executive_director'), ('general_manager', 'general_manager'), ('regional_manager', 'regional_manager'), ('projects_manager', 'projects_manager'), ('project_manager', 'project_manager'), ('construction_manager', 'construction_manager'), ('operations_manager', 'operations_manager'), ('engineering_manager', 'engineering_manager'), ('planning_manager', 'planning_manager'), ('procurement_manager', 'procurement_manager'), ('contracts_manager', 'contracts_manager'), ('business_development_manager', 'business_development_manager'), ('sales_manager', 'sales_manager'), ('partnerships_manager', 'partnerships_manager'), ('quality_manager', 'quality_manager'), ('hse_manager', 'hse_manager'), ('human_resources', 'human_resources'), ('other', 'other')], default='', max_length=40)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, choices=[('riyadh', 'riyadh'), ('alkharj', 'alkharj'), ('sudair', 'sudair'), ('qassim', 'qassim'), ('hail', 'hail'), ('jeddah', 'jeddah'), ('makkah', 'makkah'), ('madinah', 'madinah'), ('taif', 'taif'), ('yanbu', 'yanbu'), ('rabigh', 'rabigh'), ('thuwal', 'thuwal'), ('jazan', 'jazan'), ('abha', 'abha'), ('khamis_mushait', 'khamis_mushait'), ('najran', 'najran'), ('tabuk', 'tabuk'), ('neom', 'neom'), ('duba', 'duba'), ('dammam', 'dammam'), ('khobar', 'khobar'), ('dhahran', 'dhahran'), ('jubail', 'jubail'), ('rastanura', 'rastanura'), ('juaymah', 'juaymah'), ('abqaiq', 'abqaiq'), ('alahsa', 'alahsa'), ('qatif', 'qatif'), ('khurais', 'khurais'), ('khursaniyah', 'khursaniyah'), ('safaniyah', 'safaniyah'), ('tanajib', 'tanajib'), ('hafar_albatin', 'hafar_albatin'), ('arar', 'arar'), ('other', 'other')], default='', max_length=40)),
                ('service_type', models.CharField(blank=True, choices=[('construction', 'construction'), ('civil_works', 'civil_works'), ('mep', 'mep'), ('electrical', 'electrical'), ('mechanical', 'mechanical'), ('hvac', 'hvac'), ('plumbing', 'plumbing'), ('engineering_design', 'engineering_design'), ('consulting', 'consulting'), ('project_management', 'project_management'), ('facilities_management', 'facilities_management'), ('operations_maintenance', 'operations_maintenance'), ('equipment_rental', 'equipment_rental'), ('material_supply', 'material_supply'), ('transportation_logistics', 'transportation_logistics'), ('manpower', 'manpower'), ('hse_safety', 'hse_safety'), ('it_technology', 'it_technology'), ('other', 'other')], default='', max_length=40)),
                ('is_aramco_vendor', models.BooleanField(default=False)),
                ('aramco_vendor_id', models.CharField(blank=True, max_length=40, null=True)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('notified', models.BooleanField(db_index=True, default=False)),
                ('notify_attempts', models.PositiveSmallIntegerField(default=0)),
                ('notify_error', models.CharField(blank=True, default='', max_length=300)),
                ('source_ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_inquiries', to=settings.AUTH_USER_MODEL)),
                ('cv', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiry', to='inquiries.privatefile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('view_cv', "Can download an applicant's CV")],
            },
        ),
        migrations.CreateModel(
            name='CvAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_accesses', to='inquiries.inquiry')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['kind', 'status', '-created_at'], name='idx_inq_board'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['email'], name='idx_inq_email'),
        ),
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aramco_vendor_id__isnull', False), ('is_aramco_vendor', True)), models.Q(('aramco_vendor_id__isnull', True), ('is_aramco_vendor', False)), _connector='OR'), name='inq_aramco_id_iff_aramco_vendor'),
        ),
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'vendor'), _negated=True), models.Q(models.Q(('company_name', ''), _negated=True), models.Q(('city', ''), _negated=True), models.Q(('service_type', ''), _negated=True)), _connector='OR'), name='inq_vendor_has_company_city_service'),
        ),
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'contact'), _negated=True), models.Q(('send_to', ''), _negated=True), _connector='OR'), name='inq_contact_has_send_to'),
        ),
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'career'), _negated=True), ('cv__isnull', False), _connector='OR'), name='inq_career_has_cv'),
        ),
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'career'), _negated=True), ('message', ''), _connector='OR'), name='inq_career_has_no_message'),
        ),
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'career'), ('cv__isnull', True), _connector='OR'), name='inq_only_career_has_cv'),
        ),
    ]
