# Generated by Django 5.2.17 on 2026-09-12 01:20

import django.core.validators
import django.db.models.deletion
import media_library.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(max_length=255, upload_to=media_library.storage.hashed_upload_path)),
                ('checksum', models.CharField(db_index=True, max_length=64, unique=True)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(max_length=64)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('bytes', models.PositiveIntegerField()),
                ('alt_en', models.CharField(blank=True, default='', max_length=300)),
                ('alt_ar', models.CharField(blank=True, default='', max_length=300)),
                ('category', models.CharField(choices=[('project', 'Project photo'), ('client', 'Client logo'), ('gallery', 'Gallery photo'), ('page', 'Page image'), ('other', 'Other')], default='other', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MediaBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9]*$', message='A namespace is a single root key and must not contain a dot.')])),
                ('path', models.CharField(blank=True, default='', max_length=200, validators=[django.core.validators.RegexValidator('^$|^[A-Za-z][A-Za-z0-9]*(\\[\\d+\\])*(\\.[A-Za-z][A-Za-z0-9]*(\\[\\d+\\])*)*$', message='A content path looks like `items[3]` or `items[3].photos`.')])),
                ('role', models.CharField(choices=[('cover', 'Cover'), ('gallery', 'Gallery'), ('logo', 'Logo')], max_length=16)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('caption_en', models.CharField(blank=True, default='', max_length=300)),
                ('caption_ar', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='media_library.mediaasset')),
            ],
            options={
                'ordering': ['namespace', 'path', 'role', 'position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['category'], name='idx_asset_category'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['status'], name='idx_asset_status'),
        ),
        migrations.AddIndex(
            model_name='mediabinding',
            index=models.Index(fields=['namespace', 'path'], name='idx_binding_address'),
        ),
        migrations.AddConstraint(
            model_name='mediabinding',
            constraint=models.UniqueConstraint(fields=('namespace', 'path', 'role', 'position'), name='uniq_binding_slot'),
        ),
        migrations.AddConstraint(
            model_name='mediabinding',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ['cover', 'logo'])), fields=('namespace', 'path', 'role'), name='uniq_single_valued_role'),
        ),
    ]
