# Generated by Django 5.2.17 on 2026-09-02 18:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9]*$', message='A namespace is a single root key and must not contain a dot.')])),
                ('locale', models.CharField(max_length=8)),
                ('published_data', models.JSONField(default=dict)),
                ('draft_data', models.JSONField(blank=True, default=None, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['namespace', 'locale'],
                'indexes': [models.Index(fields=['locale'], name='idx_block_locale')],
                'constraints': [models.UniqueConstraint(fields=('namespace', 'locale'), name='uniq_block_namespace_locale')],
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('snapshot', models.JSONField()),
                ('is_current', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('publish', 'publish'), ('rollback', 'rollback')], default='publish', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_versions', to=settings.AUTH_USER_MODEL)),
                ('rolled_back_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rollbacks', to='content.contentversion')),
            ],
            options={
                'ordering': ['-number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='uniq_single_current_version')],
            },
        ),
    ]
